### ISSUE TITLE
falling() and rising() docs

### ISSUE THREAD

**Issue by hinxx** [darcato/pysmlib#4]
The behavior of the `fsmIO.falling()` as documented is not matching what the code does:

https://github.com/darcato/pysmlib/blob/96ddde26347ba3460268178adac637d5e8922852/smlib/io.py#L379

The `fsmIO.falling()` will be `True` as soon as the value of the PV is less than previous value, and not when value is 0 as per docs:

https://github.com/darcato/pysmlib/blob/96ddde26347ba3460268178adac637d5e8922852/docs/docs/html/io.html#L487

FWIW, the comment in the code is correct.

Same applies to the docs of the `fsmIO.rising()`.

**Comment by darcato** [comment]
You are right, the documentation is correct only in the context of binary input or output PVs that have only `0` or `1` values. I would keep the method as-is but specify better its behaviour in the docs.
